### ISSUE TITLE
Add documentation language for checking server connection settings

### ISSUE THREAD

**Issue by svpernova09** [phergie/phergie.org#14]
Add documentation language that instructs the user to double check their connection info including SSL ports.

See https://github.com/phergie/phergie-irc-bot-react/issues/42 for more info

**Comment by flip111** [comment]
This would improve on https://github.com/phergie/phergie-irc-bot-react/issues/40 not on https://github.com/phergie/phergie-irc-bot-react/issues/42 because issue 42 as you linked has actually valid settings for SSL including the port (see [first post](https://github.com/phergie/phergie-irc-bot-react/issues/42#issue-119510580))

**Comment by svpernova09** [comment]
#42 is where the discussion happened that mentioned this discussion change which would be useful if I'm not the one that gets to this issue first.
